apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - image: devopskth/demo-backend:52b2c0f9c5a4a1d2f29daf6e3deb9af35db60c46
        name: backend
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
